# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(840, 650, 171, 61))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 60, 1021, 511))
        self.widget.setObjectName("widget")
        self.spinBoxComponents = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxComponents.setGeometry(QtCore.QRect(210, 600, 101, 31))
        self.spinBoxComponents.setObjectName("spinBoxComponents")
        self.pushButtonClean = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClean.setGeometry(QtCore.QRect(660, 650, 171, 61))
        self.pushButtonClean.setObjectName("pushButtonClean")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 610, 181, 19))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Рассчитать"))
        self.pushButtonClean.setText(_translate("MainWindow", "Очистить"))
        self.label.setText(_translate("MainWindow", "Количество компонент - "))
