# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonCalculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(840, 650, 171, 61))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 1021, 591))
        self.widget.setObjectName("widget")
        self.spinBoxSensors = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxSensors.setGeometry(QtCore.QRect(160, 620, 101, 31))
        self.spinBoxSensors.setMinimum(2)
        self.spinBoxSensors.setObjectName("spinBoxSensors")
        self.pushButtonClean = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClean.setGeometry(QtCore.QRect(660, 650, 171, 61))
        self.pushButtonClean.setObjectName("pushButtonClean")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 670, 181, 19))
        self.label.setObjectName("label")
        self.pushButtonLoad = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoad.setGeometry(QtCore.QRect(370, 670, 101, 41))
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.pushButtonSimulate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSimulate.setGeometry(QtCore.QRect(480, 650, 171, 61))
        self.pushButtonSimulate.setObjectName("pushButtonSimulate")
        self.spinBoxComponents = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBoxComponents.setGeometry(QtCore.QRect(160, 670, 101, 31))
        self.spinBoxComponents.setMinimum(2)
        self.spinBoxComponents.setObjectName("spinBoxComponents")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 620, 181, 19))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Рассчитать"))
        self.pushButtonClean.setText(_translate("MainWindow", "Очистить"))
        self.label.setText(_translate("MainWindow", "Количество компонент - "))
        self.pushButtonLoad.setText(_translate("MainWindow", "Загрузить файл"))
        self.pushButtonSimulate.setText(_translate("MainWindow", "Случайная симуляция"))
        self.label_2.setText(_translate("MainWindow", "Количество сенсоров - "))
